modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="slime_decor"
version="1.0.0"
displayName="Slime's Decor"
displayURL="https://modrinth.com/mod/slimes-decor"
logoFile="logo.png"
credits="TheSlime (Models and Textures)"
authors="CodingCat"
description="Decor Mod with models from TheSlimeYT"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.slime_decor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration